{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "35982aa0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\\Untitled.ipynb : 0.0009527206420898438  мегобайт  2024-06-20 12:00:39.102205\n"
     ]
    }
   ],
   "source": [
    "import os;import math;import sys;import datetime;\n",
    "var='\\\\Untitled.ipynb'\n",
    "print (var,':',os.path.getsize(os.path.abspath(os.curdir)+var)/math.pow(2, 20),' мегобайт ',datetime.datetime.now())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f7152d90",
   "metadata": {},
   "source": [
    "    Листинг 13.7. Предоставление возможности дополнительных попыток ввода правильных данных\n",
    "    import static java.lang.System.out;\n",
    "    import java.util.Scanner;\n",
    "    import java.text.NumberFormat;\n",
    "    public class InventoryLoop\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            final double boxPrice = 3.25;\n",
    "            boolean gotGoodInput = false;\n",
    "            Scanner keyboard = new Scanner(System.in);\n",
    "            NumberFormat currency = NumberFormat.getCurrencyInstance();\n",
    "            do {\n",
    "                out.print(\"Сколько коробок вы насчитали? \");\n",
    "                String numBoxesIn = keyboard.next();"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "77a54150",
   "metadata": {},
   "source": [
    "\n",
    "            try {\n",
    "                int numBoxes = Integer.parseInt (numBoxesIn);\n",
    "                out.print(\"Общая стоимость равна: \");\n",
    "                out.print1n(currency.format (numBoxes * boxPrice));\n",
    "                gotGoodInput = true;\n",
    "            }\n",
    "            catch (NumberFormatException e) {\n",
    "                out.println();\n",
    "                out.println (\"Это не целое число.\");\n",
    "            }\n",
    "            } while (!gotGoodInput);\n",
    "            out.println(\"Отлично.\");\n",
    "            keyboard.close();\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1b70a78e",
   "metadata": {},
   "source": [
    "На рис. 13.12 показан результат выполнения листинга 13.7. Первые три попытки неудачные: пользователь вводит строку, которую компьютер не может интерпретировать как целое число. И наконец, на четвертой попытке пользователь вводит нечто такое (число 3), против чего код не возражает.\n",
    "\n",
    "# Наши друзья - хорошие исключения\n",
    "У вас могло сложиться впечатление, будто исключения всегда происходят вследствие ошибок и других нежелательных ситуаций. В большинстве случаев это так. Но иногда исключение генерируется при нормальной работе программы в соответствии с замыслом программиста. Например, исключение может применяться для обнаружения конца файла. Рассмотрим следующий код, копирующий файл из потока dataIn в поток dataOut.\n",
    "\n",
    "    Сколько коробок вы насчитали?\n",
    "    Это не целое число.\n",
    "    Сколько коробок вы насчитали? три\n",
    "    Это не целое число.\n",
    "    Сколько коробок вы насчитали? рыба\n",
    "    Это не целое число.\n",
    "    Сколько коробок вы насчитали? Общая стоимость равна: 9,75 руб. Отлично.\n",
    "    \n",
    "Рис. 13.12. Результат выполнения кода из листинга 13.7\n",
    "\n",
    "Стр. 401\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6fdbc57c",
   "metadata": {},
   "source": [
    "    try { while (true){ dataOut.writeByte (dataIn.readByte()); } } \n",
    "    catch (EOFException e) {numFilesCopied = 1;}\n",
    "Копирование выполняется в цикле while по одному байту. Условие цикла содержит выражение true, поэтому, казалось бы, цикл будет продолжаться бесконечно. Однако программа все же когда-нибудь достигнет конца файла. Когда это произойдет, метод readByte сгенерирует исключение EOFException (достигнут конец файла). В результате компьютер выйдет из блока try и одновременно из цикла while. После этого можно сделать все, что нужно, в блоке catch и возобновить нормальный процесс вычислений.\n",
    "\n",
    "Выполните следующие упражнения.\n",
    "- Добавьте блок try catch, позволяющий предотвратить аварийное завершение следующего кода."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4cf23956",
   "metadata": {},
   "source": [
    "    import java.util.Scanner;\n",
    "    public class Main\n",
    "    {\n",
    "        public static void main(String[] args)\n",
    "        {\n",
    "            Scanner keyboard = new Scanner(System.in);\n",
    "            String[] words = new String[5];\n",
    "            int i = 0;\n",
    "            do { words[i] = keyboard.next(); } while (!words[i++].equals(\"Выход\"));\n",
    "            for (int j = 0; j < 5; j++) { System.out.println(words[j].length()); }\n",
    "            keyboard.close ();\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Стр. 402\n",
    "\n",
    "---------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "45a0024e",
   "metadata": {},
   "source": [
    "- В листинге 13.6 цена каждой коробки и максимально допустимое количество коробок представлены фиксированными значениями. Внесите улучшения в код, обеспечивающие пользователю возможность ввода этих значений. Помните о том, что некоторые из значений лишены смысла. Например, отрицательное количество ящиков никогда не будет слишком большим. Используйте блок try catch для обработки некорректных данных, вводимых пользователем."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9f781eed",
   "metadata": {},
   "source": [
    "# Обработайте исключение или передайте его дальше\n",
    "Итак, вы дошли до главы 13. Вы многое узнали и проделали много работы. Не устали ли вы?\n",
    "Как насчет того, чтобы вздремнуть на несколько минут? Но, наверное, не-\n",
    "сколько минут - это слишком много, давайте остановимся на пяти секундах. В листинге 13.8 приведена программа, которая должна приостановить свою работу на пять секунд. Проблема заключается в том, что данный вариант программы вы не сможете скомпилировать. Потратьте пару минут на изучение листинга 13.8, а затем я расскажу, что именно в программе не так.\n",
    "\n",
    "    Листинг 13.8. Вздремнуть нам пока что не удастся\n",
    "    // Этот код не компилируется\n",
    "    import static java.lang.System.out;\n",
    "    public class NoSleepForTheWeary \n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            out.print (\"Немного вздремну. \");\n",
    "            out.println(\"Всего пять секунд…\");\n",
    "            takeANap();\n",
    "            out.println(\"Я опять бодр и полон сил!\");\n",
    "        }\n",
    "        static void takeANap() { Thread.sleep(5000);}   \n",
    "    }\n",
    "    \n",
    "Стр. 403\n",
    "\n",
    "-------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9beb90a3",
   "metadata": {},
   "source": [
    "Стратегия, примененная в листинге 13.8, сама по себе правильная. Программа вызывает метод sleep класса Thread, входящего в Java API. Число, передаваемое методу, -- это длительность паузы в миллисекундах. Выражение Thread. sleep (5000) означает, что выполнение текущего потока будет приостановлено на пять секунд. Проблема состоит в том, что метод sleep может сгенерировать исключение InterruptedException (исключение прерывания). Поэтому при попытке скомпилировать этот код компилятор вернет сообщение, подобное следующему.\n",
    "\n",
    "Unreported exception java.lang.InterruptedException; must be caught or declared to be thrown (Незарегистрированное исключение java. lang. InterruptedException; должно быть перехвачено или объявлено сгенерированным) Либо сообщение может иметь следующий вид: Unhandled exception type InterruptedException (Hеобработанный тип исключения InterruptedException)\n",
    "\n",
    "Как бы там ни было, подобные сообщения нежелательны.\n",
    "\n",
    "- технические подробности - Чтобы понять общий принцип работы исключений, вовсе не обязательно вникать в суть исключения InterruptedException. Все, что вам действительно нужно знать, - это то, что вызов Thread. sleep может вызвать одно из исключений типа InterruptedException. Подобное исключение генерируется, когда какой-то другой код прерывает паузу данного кода. В Java несколько потоков кода могут выполняться одновременно. Поэтому может случиться так, что один поток вызывает метод Thread.sleep, но в то же самое время другой поток вызывает метод interrupt. Второй поток хочет временно приостановить первый, чтобы выполнить какую-то срочную работу, но первый поток и без того уже в режиме паузы. На создавшуюся ситуацию метод Thread. sleep отреагирует генерированием исключения InterruptedException.\n",
    "\n",
    "Стр. 404\n",
    "\n",
    "-------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5c762475",
   "metadata": {},
   "source": [
    "В языке Java есть исключения двух видов: проверяемые и непроверяемые.\n",
    "- Проверяемые исключения должны быть перехвачены и обработаны в коде, иначе программа будет аварийно завершена.\n",
    "- Непроверяемые исключения можно не перехватывать и не обрабатывать. Но в случае необходимости такое исключение может быть обработано.\n",
    "\n",
    "Исключение InterruptedException относится к категории проверяемых. Когда код вызывает метод, который может сгенерировать проверяемое исключение, нужно в этом же коде запрограммировать его перехват и обработку, иначе код не будет компилироваться.\n",
    "Таким образом, если код метода может сгенерировать проверяемое исключение, необходимо запрограммировать реакцию на него одним из двух способов.\n",
    "\n",
    "- Заключить место, в котором может произойти исключение, в блок try. Добавить блок catch (возможно, пустой), перехватывающий исключение данного типа.\n",
    "- Добавить в заголовок метода директиву throws и тип исключения (можно добавить базовый тип Exception, обозначающий любое исключение).\n",
    "\n",
    "Проиллюстрируем эти два пункта в следующих двух листингах. В листинге 13.9 метод sleep, который может сгенерировать исключение, находится в блоке try. Непосредственно после него расположен блок catch, в списке параметров которого указан тип InterruptedException."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "16f5791b",
   "metadata": {},
   "source": [
    "    Листинг 13.9. Обработка исключения в блоке try catch\n",
    "    import static java.lang.System.out;\n",
    "    public class GoodNightsSleepA\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            out. print (\"Немного вздремну. \");\n",
    "            out.println(\"Всего пять секунд…\");\n",
    "            takeANap();\n",
    "            out.println(\"Я опять бодр и полон сил!\");\n",
    "        }\n",
    "        static void takeANap()\n",
    "        {\n",
    "            try{Thread.sleep (5000); } catch (InterruptedException e)\n",
    "            out.println(\"Эй! Кто разбудил меня?\");\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "Стр. 405\n",
    "\n",
    "--------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a3f04ad6",
   "metadata": {},
   "source": [
    "Сейчас я должен написать, как обычно в этой книге, что результат выполнения листинга такого-то показан на рисунке таком-то. Но проблема состоит в том, что рис. 13.13 иллюстрирует менее важный случай, когда исключения не произошло. Код компилируется потому, что вызов метода sleep заключен в блок try и добавлен блок catch. Конечно, интереснее было бы показать, как обрабатывается исключение, но его в данном случае сложно сгенерировать. Нужно создать еще один поток, а в нем -- кнопку, на которой пользователь щелкнет в момент паузы первого потока. Поэтому, чтобы не усложнять пример, ограничимся иллюстрацией более простого случая.\n",
    "\n",
    "    Немного вздремну. Всего пять секунд. Я опять бодр и полон сил!\n",
    "    \n",
    "Рис. 13.13. Вторая строка появится после паузы длительностью пять секунд\n",
    "Теперь проиллюстрируем второй способ реагирования на исключение, состоящий в добавлении директивы throws в заголовок метода (листинг 13.10). Директива throws сообщает компилятору о том, что в случае возникновения исключения оно будет передано вызывающему методу.\n",
    "\n",
    "    Листинг 13.10. Использование директивы throws\n",
    "    import static java.lang.System.out;\n",
    "    public class GoodNightsSleepB {\n",
    "    public static void main(String args[]){\n",
    "    out. print (\"Немного вздремну. \");\n",
    "    out.println(\"Всего пять секунд…\");\n",
    "    try (\n",
    "    takeANap();\n",
    "    catch (InterruptedException e) {\n",
    "    out.println(\"Эй! Кто разбудил меня?\");\n",
    "    out.println(\"Я опять бодр и полон сил!\");\n",
    "    static void takeANap()\n",
    "    throws InterruptedException {\n",
    "    Thread.sleep (5000);\n",
    "    \n",
    "Стр. 406"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "040667c0",
   "metadata": {},
   "source": [
    "Результат будет тем же, что и в предыдущем случае (см. рис. 13.13). Не забывай-\n",
    "те, что компьютер \"спит\" пять секунд, прежде чем отобразить второе сообщение. Важная часть листинга 13.10 - заголовок метода takeANap. Он заканчивается директивой throws InterruptedException, которая как бы говорит компилятору: \"Да, я понимаю, что в теле метода имеется инструкция, которая может стать причиной возникновения исключения InterruptedException, но я не хочу обрабатывать это исключение с помощью блока try catch. Компилятор Java, пожалуйста, не нагружай меня сообщением по этому поводу. Вместо того чтобы заниматься самому обработкой исключения, я передаю ответственность за выполнение этой обработки методу main (т.е. методу, который вызывает метод takeANap)\".\n",
    "Соответственно, обязанность обработать исключение теперь лежит на методе main. Для этого в его теле вызов метода takeANap должен быть заключен в блок try. Кроме того, в тело метода main должен быть добавлен блок catch параметром InterruptedException. Теперь компилятор не будет выдвигать никаких претензий. Обязанность обработать исключение перешла к методу main, и он готов его обработать.\n",
    "Чтобы лучше понять принцип работы директивы throws, представьте себе игру в волейбол, в которой исключение интерпретируется как волейбольный мяч. Когда игрок подает мяч, он как бы генерирует исключение. Мяч перелетает над сеткой и попадает к вам. Вы можете либо перебросить его через сетку (т.е. обработать исключение), либо передать другому игроку вашей команды, который, в свою очередь, также может либо обработать исключение, либо передать его другому игроку."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5fd9ae7b",
   "metadata": {},
   "source": [
    "- запомни - Инструкция, расположенная в теле метода, может сгенерировать исключение, не обрабатываемое блоком catch вследствие несовпадения типов. Кроме того, исключение может быть сгенерировано инструкцией, не входящей в блок try. В любом из этих случаев управление передается вызывающему методу, т.е. за пределы метода, содержащего инструкцию, которая сгенерировала исключение.\n",
    "\n",
    "В директиве throws можно задать несколько типов исключений, разделив их запятыми:\n",
    "\n",
    "    throws InterruptedException, IOException, ArithmeticException\n",
    "    \n",
    "Стр. 407"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "56901ba6",
   "metadata": {},
   "source": [
    "В Java API определено несколько сотен типов исключений. Некоторые из них наследуют класс RuntimeException. Эти исключения относятся к категории непроверяемых (см. выше). Любое исключение, не наследую- щее класс RuntimeException, относится к категории проверяемых. К этой категории принадлежат исключения, которые компьютеру сложно предвидеть и правильно обработать. Например, к подобным исключениям относятся NumberFormatException (см. листинги 13.2, 13.4 и др.), ArithmeticException, IndexOutOfBoundsException, NullPointerException и многие другие. При написании кода Java большая его часть подвержена этим исключениям, тем не менее заключение этого кода в блок try (либо использование директив throws) не является обязательным.\n",
    "В Java API определено довольно много проверяемых исключений. Компьютер может легко обнаруживать возможность появления исключений такого рода. Поэтому компилятор Java настаивает на том, чтобы программа предпринимала определенные меры в отношении таких исключений путем использования либо инструкции try, либо директивы throw. В число проверяемых исключений Java входят исключения InterruptedException (см. листинги 13.9 и 13.10), IOException, SQLException и многочисленная группа других интересных исключений.\n",
    "\n",
    "Существует прямая связь между словом \"попробуй\" и оператором try в блокаx try catch. Попробуйте решить следующие небольшие задачки.\n",
    "- Следующий код не компилируется, поскольку вызывает необработанное исключение FileNotFoundException."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2b755974",
   "metadata": {},
   "source": [
    "\n",
    "    // плОхой код:\n",
    "    import java.io.File;\n",
    "    import java.util.Scanner;\n",
    "    public class Main \n",
    "    {\n",
    "        public static void main(String[] args)\n",
    "        {\n",
    "            Scanner diskScanner = new Scanner(new File(\"numbers.txt\"));\n",
    "            int [] numerators = new int[5];\n",
    "            int[] denominators = new int [5];\n",
    "            int i = 0;\n",
    "            while (diskScanner.hasNextInt())\n",
    "            {\n",
    "                numerators[i] = diskScanner.nextInt();\n",
    "                denominators [i] = diskScanner.nextInt();\n",
    "                i++;\n",
    "                for (int j = 0; j < numerators.length; j++) {System.out.println(numerators(j] / denominators(j]);}\n",
    "            }\n",
    "            diskScanner.close();\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Стр. 408"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "153c659d",
   "metadata": {},
   "source": [
    "Добавьте обработку исключения FileNotFoundException, чтобы получить возможность компиляции кода. Учтите, что в зависимости от значений в файле numbers. txt во время выполнения программы могут генерироваться некоторые другие исключения. Добавьте один или несколько блоков try catch, чтобы отображать сообщения о появлении подобных исключений и избежать аварийного завершения программы.\n",
    "- Добавьте блоки try catch или операторы throws (или же сочетание этих конструкций), чтобы улучшить следующий код."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c89066f7",
   "metadata": {},
   "source": [
    "    // плохой код:\n",
    "    import java.io. DataInputStream;\n",
    "    import java.io. DataOutputStream;\n",
    "    import java.io.EOFException;\n",
    "    import java.io.File;\n",
    "    import java.io.FileInputStream;\n",
    "    import java.io.FileOutputStream;\n",
    "    public class Main\n",
    "    {\n",
    "        public static void main(String[] args)\n",
    "        {\n",
    "            File fileIn = new File(\"input\");\n",
    "            FileInputStream fileInStrm = new;\n",
    "            FileInputStream(fileIn);\n",
    "            DataInputStream dataInStrm = new\n",
    "            DataInputStream (fileInStrm);"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ecdd7b3e",
   "metadata": {},
   "source": [
    "       File fileOut = new File(\"output\");\n",
    "            FileOutputStream fileOutStrm = new\n",
    "            FileOutputStream (fileOut);\n",
    "            DataOutputStream dataOutStrm = new DataOutputStream(fileOutStrm);\n",
    "            int numFilesCopied = 0;\n",
    "            try\n",
    "            {\n",
    "                while (true);\n",
    "                dataOutStrm. writeByte (dataInStrm.readByte());\n",
    "            }\n",
    "            catch (EOFException e)\n",
    "            {\n",
    "                numFilesCopied = 1;\n",
    "            }\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "29e8a8b9",
   "metadata": {},
   "source": [
    "Как только будет получен код, пригодный для компиляции, создайте файл input и запустите код. Посмотрите, был ли создан файл output.\n",
    "\n",
    "Стр. 409"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "381f273c",
   "metadata": {},
   "source": [
    "# Блок finally\n",
    "Однажды, когда я был еще совсем молодым парнем и только получил водительские права, я взял у родителей автомобиль и поехал к своему другу. По дороге я задумался бог знает о чем, и вдруг машину тряхнуло. Оказалось, что другой автомобиль, взявшийся неизвестно откуда, врезался в правую дверцу моей машины. Произошло исключение типа RunARedLightException (проезд на красный свет).\n",
    "Оба автомобиля остались на ходу и могли самостоятельно перемещаться. Дорога была оживленной, и, чтобы не создавать пробку, мы отъехали на обочину. Я нашел в отсеке под приборной панелью необходимые документы и вышел из машины.\n",
    "И тут произошла вторая авария. Я был так поглощен и обескуражен произошедшим, что не заметил ехавшего прямо на меня автобуса, который выбил дверцу из моих рук, а меня самого отбросил на капот. Произошло исключение типа DealWithLawyersException (работа для адвокатов).\n",
    "Все закончилось благополучно. Я был весь в синяках, но серьезных травм не получил. Мои родители заплатили за поврежденный чужой автомобиль, поэтому я не понес финансовых потерь (я передал исключение RunRedLightException родителям с помощью директивы throws).\n",
    "\n",
    "Этот инцидент поможет нам понять, как обрабатывается исключение. Что произойдет, если во время обработки одного исключения возникнет другое? Ведь инструкции в блоке catch также не застрахованы от исключений.\n",
    "Одно из решений (как вы дальше увидите - плохое) состоит в том, чтобы поместить еще один блок try в блок catch. Это предохранит программу от неожиданных инцидентов во время выполнения блока catch. Однако для дополнительного блока try нужен свой блок catch. Таким образом, проблема не решается, а отодвигается, причем уровня вложенности, на котором она будет решена окончательно, не существует.\n",
    "Другое, лучшее решение проблемы состоит в создании блока finally. Как и блок catch, он располагается после блока try. Его существенное отличие от блоков try и catch состоит в том, что его инструкции всегда выполняются независимо от того, возникло ли исключение и было ли оно обработано. Данная концепция иллюстрируется в листинге 13.11."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "60cbd129",
   "metadata": {},
   "source": [
    "    Листинг 13.11. Использование блока finally\n",
    "    import static java.lang.System.out;\n",
    "    public class DemoFinally\n",
    "    {\n",
    "        public static void main(String args[]) \n",
    "        {\n",
    "            try{ doSomething ();}\n",
    "            catch (Exception e) { out.println(\"Исключение перехвачено в main.\");}\n",
    "        }\n",
    "        static void doSomething()\n",
    "        {\n",
    "            try{out.println(0 / 0); }\n",
    "            catch (Exception e) { out.println(\"Исключение перехвачено в doSomething.\"); out.println(0 / 0);}\n",
    "            finally { out.println(\"Выведено в блоке finally.\"); }\n",
    "            out.println(\"Это сообщение не будет выведено.\");\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Стр. 410"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d77414e",
   "metadata": {},
   "source": [
    "        public static void main(String args[]) \n",
    "        {\n",
    "            try{ doSomething (); }\n",
    "            catch (Exception e){ out. println(\"Исключение перехвачено в main.\");}\n",
    "        }\n",
    "\n",
    "        static void doSomething()\n",
    "        {\n",
    "            try { out.println (0 / 0); }\n",
    "            catch (Exception e)\n",
    "            { \n",
    "                out.println(\"Исключение перехвачено в doSomething.\");\n",
    "                out. println(0 / 0);\n",
    "            }\n",
    "            finally { out.println(\"Выведено в блоке finally.\");}\n",
    "            out.println(\"Это сообщение не будет выведено.\");\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a0417caf",
   "metadata": {},
   "source": [
    "Обычно, думая о блоке try, я думаю и о восстановлении выполнения программы после аварийной ситуации. Восстановление программы происходит в блоке catch. Затем выполнение продолжается с первой инструкции после блоков try catch. Если же что-нибудь происходит при выполнении блока catch, события развиваются иначе. Результат работы листинга 13.11 показан на рис. 13.14. Сначала метод main вызывает метод doSomething. После этого метод doSomething начинает создавать многочисленные неприятности. Сначала он пытается поделить нуль на нуль, что невозможно в любом языке программирования. Эта операция порождает исключение ArithmeticException, которое перехватывается единственным в данном методе блоком catch.\n",
    "\n",
    "    Исключение перехвачено в doSomething.\n",
    "    Выведено в блоке finally.\n",
    "    Исключение перехвачено в main.\n",
    "Рис. 13.14. Результат выполнения листинга 13.11\n",
    "\n",
    "В блоке catch метод doSomething опять пытается поделить нуль на нуль. Ha этот раз инструкция, выполняющая незаконное деление, не находится в защит- Hом блоке try. Это допустимо, потому что исключение ArithmeticException не является проверяемым. Оно наследует класс RuntimeException, поэтому перехватывать и обрабатывать его необязательно (см. предыдущий раздел).\n",
    "\n",
    "Стр. 411\n",
    "\n",
    "-------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1b3aefe0",
   "metadata": {},
   "source": [
    "В любом случае, перехвачено оно или не перехвачено, второе исключение ArithmeticException приводит к тому, что управление выпадает из метода doSomething. Но, прежде чем покинуть метод doSomething, компьютер выполняет блок finally - последнюю волю гибнущего блока try. Вот почему на рис. 13.14 отображена фраза Выведено в блоке finally.\n",
    "Интересно отметить, что фразы Это сообщение не будет выведено на рис. 13.14 нет. Блок catch сгенерировал собственное исключение (вместо того чтобы обработать исключение, блок catch сгенерировал еще одно). Оно не было перехвачено, поэтому компьютер не продолжил нормальное выполнение инструкций после блоков try catch finally, а немедленно вышел из метода doSomething.\n",
    "Итак, компьютер вернулся в метод main. Но из метода doSomething он вышел не в нормальном режиме, а по исключению ArithmeticException, которое произошло в методе doSomething. Поэтому компьютер выполняет блок catch, расположенный в методе main. Завершающий аккорд! На этом какофония исключений наконец-то заканчивается.\n",
    "- попробуй - В конце предыдущего раздела был добавлен код обработки исключений в программу, создающую копию файла. Наряду с результатом выполнения своего кода вы можете увидеть предупреждения, сообщающие о том, что вы забыли закрыть потоки dataInStrm и dataOutStrm. Исправьте код, добавив вызовы dataInStrm.close () и dataOutStrm.close() в блоки finally."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "978598c3",
   "metadata": {},
   "source": [
    "# Использование инструкции try при работе с ресурсами\n",
    "Предположим, есть программа, которая получает входные данные из двух различных файлов либо из потока Scanner и файла на диске. Чтобы гарантировать своевременное освобождение ресурсов, необходимо поместить вызов метода close в блок finally (листинг 13.12).\n",
    "\n",
    "    Листинг 13.12. Использование двух файлов\n",
    "    import java.io.File;\n",
    "    import java.io.IOException;\n",
    "    import java.utiil.Scanner;\n",
    "    public class Main\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            Scanner scanl = null;\n",
    "            Scanner scan2 = null;\n",
    "            try {\n",
    "                scanl = new Scanner(new File(\"Filel.txt\"));\n",
    "                scan2 = new Scanner(new File(\"File2.txt\")); // Выполнить что-то полезное\n",
    "            } catch (IOException e) { // Ой!\n",
    "            } finally {\n",
    "            scanl.close();\n",
    "            scan2.close ();\n",
    "            System.out.println(\"Готово!\");\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Стр. 412\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d16d5c6",
   "metadata": {},
   "source": [
    "Tеоретически компьютер должен выполнить вызовы scanl.close() и scan2.close () в любом случае, независимо от того, пойдет ли что-либо не так при выполнении инструкций в блоке try. Однако это в теории. На практике другой программист (не вы, конечно) мог изменить код, поместив операцию освобождения ресурса scan1 в блок try.\n",
    "\n",
    "    try \n",
    "    {\n",
    "        scanl = new Scanner(new File(\"Filel.txt\"));\n",
    "        scan2 = new Scanner(new File(\"File2.txt\"));\n",
    "        // Выполнить что-то полезное\n",
    "        scan1.close();\n",
    "        scan1 = null;\n",
    "    } catch (IOException e) {\n",
    "    // Ой!\n",
    "    } finally {\n",
    "        scan1.close ();\n",
    "        scan2.close();\n",
    "        System.out.println(\"Готово!\");\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da031426",
   "metadata": {},
   "source": [
    "Вот теперь у вас сложилась действительно затруднительная ситуация. В блоке finally значение scanl равно null. Вызов scanl.close () не может быть выполнен, поэтому программа генерирует исключение NullPointerException (нулевой указатель), и ее выполнение прекращается еще до того, как выпол- нится вызов scan2.close (). При наихудшем стечении обстоятельств ресурс scan2 не освобождается, и файл File2.txt блокируется вашей программой, не давая другим программам использовать его.\n",
    "Когда в программе используется множество ресурсов (файлы, базы данных, сетевые соединения и т.п.), структура блоков try и директив throws может стать слишком сложной, потому что придется также включать блоки try в блоки catch и применять другие запутанные комбинации. Оптимальное решение данной проблемы появилось в версии Java 7: ресурсы можно включать в заголовок блока try (листинг 13.13).\n",
    "\n",
    "Стр. 413\n",
    "\n",
    "---------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "13b26484",
   "metadata": {},
   "source": [
    "    Листинг 13.13. Гарантированное освобождение ресурсов\n",
    "    import java.io.File;\n",
    "    import java.io.IOException;\n",
    "    import java.util.Scanner;\n",
    "    public class NewMain \n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            try {\n",
    "                Scanner scanl = new Scanner(new File(\"Filel.txt\"));\n",
    "                Scanner scan2 = new Scanner(new File(\"File2.txt\"))) {\n",
    "                // Выполнить что-то полезное\n",
    "            } catch (IOException e) { // Ой!\n",
    "                System.out.println(\"Готово!\");\n",
    "            }\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c6550dc8",
   "metadata": {},
   "source": [
    "В листинге 13.13 объявление ресурсов scan1 и scan2 заключено в круглые скобки и помещено после ключевого слова try. Это означает, что Java автоматически освободит ресурсы scan1 и scan2, закрыв их после выполнения инструкций в блоке try. В заголовке блока try можно объявить несколько ресурсов. Тогда Java закроет их все после выполнения блока try. При необходимости могут быть добавлены блоки catch и finally. Данное средство особенно полезно при использовании соединений с базами данных, потому как позволяет быть уверенным в том, что соединение будет в любом случае автоматически разорвано.\n",
    "- попробуй - В конце раздела \"Обработайте исключение или передайте его дальше\" вы добавили в программу, создающую копию файла, код обработки исключений. Наряду с результатом выполнения своего кода вы можете увидеть предупреждения, сообщающие о том, что вы забыли закрыть потоки dataInStrm и dataOutStrm. В следующем разделе вы избавились от появления предупреждений, добавив вызовы dataInStrm.close () и dataOutStrm.close () в состав блоков finally. Вместо вызовов close устраните проблему с помощью оператора try, предназначенного для работы с ресурсами.\n",
    "\n",
    "Стр. 414\n",
    "\n",
    "--------------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d33c904b",
   "metadata": {},
   "source": [
    "# Глава 14 Область видимости переменных\n",
    "В ЭТОЙ ГЛАВЕ…\n",
    "- Сокрытие имен от других классов\n",
    "- Предоставление имен для использования другими классами\n",
    "- Как изменить программу, не изменяя классы\n",
    "\n",
    "Я обедаю с коллегами в небольшом ресторанчике рядом с офисом. Один из них говорит: \"Они могут читать нашу электронную почту\". Другой подхватывает тему: \"У них есть полный список посещенных тобой сайтов. Они знают, что ты ешь на обед, что покупаешь, что носишь и о чем думаешь. Также они знают твои самые большие секреты, скрытые страхи и желания. Не удивлюсь, если они даже знают, когда ты умрешь\". К разговору подключается третий: \"Все идет к тому, что нельзя будет высморкаться без того, чтобы это не было зафиксировано в базе данных. Недавно я открыл один веб-сайт и увидел на странице поздравление с днем рождения, адресованное мне. Откуда они узнали, что именно я посетил сайт и что у меня сегодня день рождения?\" \"О, да! -- говорит первый. - На моей машине есть идентификационный чип. При проезде через пост дорожного сбора нужная сумма автоматически снимается с моей банковской карты. Каждый месяц я получаю от компании длинный список платежей, в котором зафиксировано, где и когда я проезжал. В ближайшем будущем, наверное, я буду видеть в этом списке также, к кому я ездил и что там делал\". Я не вмешиваюсь в разговор и думаю про себя: \"Ну и что? Лично я был бы польщен, если бы мой работодатель, правительство или какая-нибудь крупная компания до такой степени интересовались моими делами, что отслеживали каждый мой шаг. Нам часто приходится прилагать огромные усилия, чтобы привлечь чье-либо внимание. Каким покинутым и забытым себя чувствуешь, когда видишь, что никому нет дела до тебя! Многие агентства, записывающие в журнал мои покупки, фиксирующие мои привычки и присылающие рекламные буклеты, часто даже не могут написать или произнести мое имя без ошибки. \"Алло, будьте любезны, позовите, пожалуйста, мистера Ларри Берга. Он дома? Ах, да, Барри Берд… Прошу прощения! Конечно, Барри Берд\"."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "058da59f",
   "metadata": {},
   "source": [
    "# Модификаторы доступа к членам классов\n",
    "Если вы дошли до этого места в книге, значит, уже знаете, что в объектно- ориентированном программировании много внимания уделяется сокрытию одних данных от других. Программист, пишущий свою часть кода, не должен менять фрагменты кода, написанные другими программистами. Это обусловлено не требованиями безопасности или секретности, а принципом модульности. Скрывая подробности, вы фактически скрываете сложность своего кода и делаете его простым для использования. Ваш код выглядит как черный ящик с простыми входами и выходами. Вы упрощаете задачу людям. Вы облегчаете их жизнь и предохраняете от ошибок, экономите их деньги, бережете их время и способствуете продлению их жизни. Впрочем, вы и себе облегчаете этим жизнь, потомучто уменьшаете вероятность конфликтов имен в своем коде.В предыдущих главах на каждом шагу встречались примеры использования закрытых полей. Если поле объявлено с модификатором private, оно невидимо за пределами класса и недоступно для изменения. Сокрытие полей и методов улучшает модульность и упрощает код.\n",
    "Но не все поля в примерах книги закрытые. Есть также немало открытых полей, т.е. объявленных с модификатором public. Как мировая знаменитость, личная жизнь которой выставлена напоказ, открытое поле доступно всем и каждому, т.е. к нему можно обращаться в любом месте программы. Многие знают, какую зубную пасту использовал Элвис Пресли. Аналогично этому любой программист может сослаться в программе на открытую переменную. Разница лишь в том, что открытую переменную можно как читать, так и изменять, а название зубной пасты Элвиса любой его поклонник может только узнать, изменить его он не может. Ключевые слова public и private называются модификаторами доступа. В примерах книги вам часто встречались поля и методы, объявленные без модификаторов доступа. Такие поля и методы имеют доступ, установленный по умолчанию. В большинстве глав не имеет значения, что такое доступ, установленный по умолчанию, но только не в данной главе. Здесь мы рассмотрим этот вопрос подробнее. В главе рассматривается также еще один модификатор доступа, который не использовался в предыдущих главах. Это модификатор protected, определяющий защищенный доступ.\n",
    "\n",
    "Стр. 416\n",
    "\n",
    "--------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "764e7c8e",
   "metadata": {},
   "source": [
    "# Классы, виды доступа и деление программ на части\n",
    "Изучая правила доступа, нам придется немного углубиться в специальную терминологию. Некоторые термины уже упоминались в главе 10, но полезно будет повторить их еще раз. Рассмотрим следующий код.\n",
    "\n",
    "    class MyClass \n",
    "    {\n",
    "        int myField; // поле, член класса\n",
    "        void myMethod() { // петод, член класса\n",
    "            int myOtherField; локальная переменная, не член класса\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Пояснения даны в комментариях к коду. Здесь имеются два вида переменных: члены класса и локальные переменные метода. Но в данной главе речь пойдет не о локальных переменных методов. Основной предмет нашего внимания - методы и поля.\n",
    "Поверьте мне, не так-то просто постоянно использовать фразу \"методы и поля\". Гораздо лучше дать этим понятиям обобщающее название. Именно поэтому методы и поля называются членами класса.\n",
    "\n",
    "Стр. 417\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2b338549",
   "metadata": {},
   "source": [
    "# Классы и члены классов\n",
    "С этого момента вы должны четко различать, где используются модификаторы доступа. Ранее вы размещали их в объявлениях членов класса. Например, можно написать так:\n",
    "\n",
    "    public static void main(String args[]) { public amountInAccount = 50.22;\n",
    "    \n",
    "Использование ключевого слова public в этих случаях не является для вас сюрпризом. Но вы, возможно, еще не знаете, что его можно применить и в определении класса, например, так.\n",
    "\n",
    "    public class Drawing{/* Код класса */}\n",
    "\n",
    "Ключевое слово public имеет в Java два немного разных назначения: одно - для членов класса, другое - для самих классов. В данной главе ключевое слово public (и другие модификаторы доступа) рассматривается применительно к членам класса, однако в конце главы будет кратко обсуждаться и его использование в заголовке класса."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1bccd16f",
   "metadata": {},
   "source": [
    "# Правила доступа к членам класса\n",
    "Этот раздел посвящен исключительно членам класса. Но это не значит, что классы в нем игнорируются. В Java все делается только в классах. Каждое поле может быть объявлено только в каком-то классе; оно принадлежит этому классу и является его членом. То же самое справедливо и для методов. Важный вопрос, которому посвящена вся данная глава: можно ли использовать имя некоторого члена класса в другом месте кода? Для ответа на него в первую очередь посмотрите, где находится это место: внутри или вне класса, в котором определен данный член. Если член класса объявлен как закрытый (с модификатором private),то обратиться к нему можно только в данном классе.\n",
    "\n",
    "    class SomeClass { private int myField = 10; }\n",
    "    class SomeOtherClass\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            SomeClass someObject = new SomeClass();\n",
    "            // Этот код не работает\n",
    "            System.out.println(someObject.myField);\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eaaa21e4",
   "metadata": {},
   "source": [
    "Если член класса объявлен как открытый (с модификатором public), то к нему можно обратиться по имени в любой точке программы.\n",
    "\n",
    "    class SomeClass\n",
    "    {\n",
    "        public int myField = 10;\n",
    "        class SomeOtherClass\n",
    "        {\n",
    "            public static void main(String args[])\n",
    "            {\n",
    "                SomeClass someObject = new SomeClass(); // Этот код работает\n",
    "                System.out.println (someObject.myField);\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Стр. 418\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b619c882",
   "metadata": {},
   "source": [
    "Эти идеи проиллюстрированы несколько иным способом на рис. 14.1-14.3.\n",
    "- Класс А -> Класс В расширяет класс А -> Класс С расширяет класс В\n",
    "- Класс L -> Класс М расширяет класс L -> Класс N расширяет класс М\n",
    "- Класс Х -> Класс Y расширяет класс Х -> Класс Z расширяет класс Y\n",
    "\n",
    "Рис. 14.1. Несколько классов вместе с подклассами\n",
    "\n",
    "Стр. 419\n",
    "\n",
    "-----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eab03ca8",
   "metadata": {},
   "source": [
    "- внимание - Примеры из этого раздела могут сформировать у читателя неправильные представления. У вас, например, может возникнуть следующий вопрос: \"В примере с оператором private int myField код не работает. А в примере с public int myField код вполне работоспособен. Поэтому для повышения шансов на получение рабочего кода лучше придавать полям статус public, а не private. Верно?\"\n",
    "\n",
    "- Класс А -> Класс В расширяет класс А -> Класс С расширяет класс В\n",
    "- Класс L -> Класс М расширяет класс L открытое поле -> Класс N расширяет класс М\n",
    "- Класс Х -> Класс Y расширяет класс Х -> Класс Z расширяет класс Y\n",
    "\n",
    "Рис. 14.2. Диапазон кода, в котором может использоваться открытое поле или метод (затененные блоки)\n",
    "\n",
    "Нет, дорогой читатель. На сей раз ты ошибаешься!\n",
    "Открытые поля просты в применении, но иногда приносят больше вреда, чем пользы. Поэтому при создании кода лучше всего по возможности ограничивать доступ к каждому полю. Если поле необязательно должно быть открытым, попробуйте сделать его закрытым. Если другие классы должны получать или устанавливать значения поля, предоставьте открытые методы доступа. Подробнее эта тема рассматривается в следующем разделе.\n",
    "\n",
    "- попробуй - В одном из примеров раздела вы не могли создать ссылку someObject.myField, поскольку в класce SomeClass переменная myField была объявлена как private. Исправьте эту ошибку, добавив методы доступа, а также изменив соответствующим образом ссылку someObject.myField.\n",
    "\n",
    "Стр. 420\n",
    "\n",
    "---------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9587e6c",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
